openapi: 3.0.0
info:
  title: User Sign API
  description: API untuk mengirim data untuk proses login aplikasi mobile
  version: 1.0.0

servers:
  - url: "https://api.xyz.com/V1.0.0"

paths:
  /user/signin:
    post:
      summary: Mengirimkan credential data pribadi untuk login
      description: Mengirimkan username password melalui halaman login.
      parameters:
        - in: header
          name: API-Key
          required: true
          description: api-key unique for manage client
          schema:
            type: string
        - in: header
          name: Request-ID
          required: true
          description: request-id is unique
          schema:
            type: string
        - in: header
          name: Timestamp
          required: true
          description: current time
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Request'
      responses:
        '200':
          description: Login success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '202':
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProviderErrorResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIErrorResponse'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIErrorResponse'
        '504':
          description: Gateway timeout
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIErrorResponse'

components:
  schemas:
    Request:
      type: object
      properties:
        username:
          type: string
          description: username
          example: rezza6789
        password:
          type: string
          description: password
          example: abc1234
    SuccessResponse:
      type: object
      description: Detail for response
      additionalProperties: false
      properties:
        responseCode:
          type: string
          maxLength: 2 
          description: 'Response Code , length:2'
          example: '00'
        responseMessage:
          type: string
          maxLength: 50
          description: status description (Ex:Success, Invalid Message, Unknown Error from Provider), length:50
          example: Success
    
    ProviderErrorResponse:
      type: object
      description: Detail for response
      additionalProperties: false
      properties:
        responseCode:
          type: string
          maxLength: 2
          description: 'Response Code , length:2'
          example: 'Q2'
        responseMessage:
          type: string
          maxLength: 50
          description: status description (Ex:User Not Found, Already Exist, Unknown Error from Provider), length:50
          example: User Not Found
    APIErrorResponse:
      type: object
      description: Detail for response
      additionalProperties: false
      properties:
        responseCode:
          type: string
          maxLength: 2
          description: 'Response Code , length:2'
          example: '01'
        responseMessage:
          type: string
          maxLength: 50
          description: status description (Ex:Bad Request, Unauthorized, Not Found, Gateway Timeout ), length:50
          example: Bad Request